SELECT 
	TEA.CNES AS CNES,
	TEA.COMPETENCIA AS COMPETENCIA,
	TEA.NO_FANTASIA AS ESTABELECIMENTO,
	TEA.RAZAO_SOCIAL AS RAZAO_SOCIAL,
	TEA.UF_HOSPITAL AS UF,
	TEA.CO_MUNICIPIO_HOSPITAL AS CODIGO_MUNICIPIO,
	TEA.NO_MUNICIPIO_HOSPITAL AS MUNICIPIO,
	TEA.CO_PROCEDIMENTO_PRINCIPAL AS CO_PROCEDIMENTO,
	TEA.NO_PROCEDIMENTO_PRINCIPAL AS PROCEDIMENTO,
	SUM(TEA.QT_PROCEDIMENTO_APROVADO) AS QTDE_PROCEDIMENTOS,
	SUM(TEA.VALOR_APROVADO) AS VALOR_PROCEDIMENTOS
FROM 
	TB_ESPELHO_APAC AS TEA 
WHERE 
	TEA.COMPETENCIA > '200912'
GROUP BY
	CNES,
	ESTABELECIMENTO,
	RAZAO_SOCIAL,
	UF,
	CODIGO_MUNICIPIO,
	MUNICIPIO,
	CO_PROCEDIMENTO,
	PROCEDIMENTO,
	COMPETENCIA