SELECT 
	aih.CO_CNES CNES, 
	aih.dt_cmpt MES_ANO,
	aih.NO_FANTASIA ESTABELECIMENTO, 
	aih.NO_RAZAO_SOCIAL RAZAO_SOCIAL,
	aih.sg_uf UF, 
	aih.nu_mun_hosp CODIGO_MUNICIPIO, 
	aih.no_municipio MUNICIPIO,
	aih.CO_PROCEDIMENTO_PRINCIPAL CODIGO_PROCEDIMENTO,
	aih.PROCEDIMENTO_PRINCIPAL PROCEDIMENTO,
	sum(aih.qt_procedimento) QTDE_PROCEDIMENTOS, 
	sum(aih.vl_valor) VALOR_PROCEDIMENTOS
FROM TB_ESPELHO_AIH AS aih
WHERE 	aih.st_situacao = 'OK' AND aih.dt_cmpt>'200912'
GROUP BY 
	CNES, 
	MES_ANO,
	ESTABELECIMENTO,
	RAZAO_SOCIAL,
	UF,
	CODIGO_MUNICIPIO, 
	MUNICIPIO, 	
	CODIGO_PROCEDIMENTO,
	PROCEDIMENTO