-- SQL que faz a extração dos dados do município e regional de saúde.

SELECT 
    M.CO_MUNICIPIO_IBGE, M.NO_MUNICIPIO, M.SG_UF, M.CO_REGIONAL_SAUDE, R.NO_REGIONAL_SAUDE
FROM
    DBGERAL.TB_MUNICIPIO M INNER JOIN DBGERAL.TB_REGIONAL_SAUDE R ON
    M.CO_REGIONAL_SAUDE = R.CO_REGIONAL_SAUDE